# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Python Projects\Big_task\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 460)
        MainWindow.setMaximumSize(QtCore.QSize(860, 460))
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.paramsFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramsFrame.sizePolicy().hasHeightForWidth())
        self.paramsFrame.setSizePolicy(sizePolicy)
        self.paramsFrame.setMinimumSize(QtCore.QSize(200, 0))
        self.paramsFrame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.paramsFrame.setStyleSheet("QLineEdit{\n"
"border: none;\n"
"border-bottom: 1px solid #a6a6a6;\n"
"font-size: 12pt;\n"
" background: transparent;\n"
"}\n"
"QLabel{\n"
"font-size: 10pt;\n"
"}\n"
"QPushButton{\n"
"border: 1px solid #a6a6a6;\n"
"border-radius: 16;\n"
"padding: 6;\n"
"}\n"
"QPushButton:pressed{\n"
"background: #a6a6a6;\n"
"}")
        self.paramsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.paramsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.paramsFrame.setObjectName("paramsFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.paramsFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.paramsFrame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label2 = QtWidgets.QLabel(self.frame_4)
        self.label2.setObjectName("label2")
        self.verticalLayout_3.addWidget(self.label2)
        self.xInput = QtWidgets.QLineEdit(self.frame_4)
        self.xInput.setObjectName("xInput")
        self.verticalLayout_3.addWidget(self.xInput)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.yInput = QtWidgets.QLineEdit(self.frame_3)
        self.yInput.setObjectName("yInput")
        self.verticalLayout_2.addWidget(self.yInput)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_2)
        self.label_2 = QtWidgets.QLabel(self.paramsFrame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.scaleInput = QtWidgets.QLineEdit(self.paramsFrame)
        self.scaleInput.setObjectName("scaleInput")
        self.verticalLayout.addWidget(self.scaleInput)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.errorLabel = QtWidgets.QLabel(self.paramsFrame)
        self.errorLabel.setStyleSheet("color: red;")
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout.addWidget(self.errorLabel)
        self.horizontalLayout.addWidget(self.paramsFrame)
        self.map = QtWidgets.QLabel(self.centralwidget)
        self.map.setMinimumSize(QtCore.QSize(650, 450))
        self.map.setMaximumSize(QtCore.QSize(650, 450))
        self.map.setText("")
        self.map.setObjectName("map")
        self.horizontalLayout.addWidget(self.map)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Большая задача"))
        self.label2.setText(_translate("MainWindow", "Долгота"))
        self.xInput.setText(_translate("MainWindow", "37.617698"))
        self.label.setText(_translate("MainWindow", "Широта"))
        self.yInput.setText(_translate("MainWindow", "55.755864"))
        self.label_2.setText(_translate("MainWindow", "Увеличение"))
        self.scaleInput.setText(_translate("MainWindow", "7"))
        self.errorLabel.setText(_translate("MainWindow", "Некорректные параметры"))
